const data = {
  products: [
    {
      // _id: '1',
      name: 'Fresh Milk',
      slug: 'fresh-milk',
      category: 'dairy',
      image: '/images/p1.jpg', // 679px × 829px
      price: 5,
      countInStock: 10,
      brand: 'rural',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality, fresh milk delivered to tour home directly from local suppliers.',
    },
    {
      // _id: '2',
      name: 'Handmade Fresh Cheese',
      slug: 'handmade-fresh-cheese',
      category: 'dairy',
      image: '/images/p2.jpg',
      price: 7,
      countInStock: 0,
      brand: 'rural',
      rating: 4.0,
      numReviews: 10,
      description: 'Handmade natural cheese. Processed without using any chemical products in the rural areas of Kurdistan.',
    },
    {
      // _id: '3',
      name: 'Fresh Natural Honey',
      slug: 'nike-slim-panfresh-natural-honeyt',
      category: 'honey',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 15,
      brand: 'rural',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality and natural honey. Fully natural honey brought to you from the rural areas of Kurdistan where bees are out of reach from urban residential areas and only live on flower hectars!',
    },
    {
      // _id: '4',
      name: 'Fruit Jam',
      slug: 'fruit-jam',
      category: 'jams',
      image: '/images/p4.jpg',
      price: 15,
      countInStock: 5,
      brand: 'rural',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality, natural jam produced from fruits that were frshly harvested in Kurdistan. The jams were produced in a clean process without excessive use of sugar or chemicals.',
    },
  ],
};
export default data;
